version: "3.8"

services:
    test_mongodb:
        image: mongo
        container_name: test_mongodb
        ports:
          - 27017:27017
        volumes:
          - db-data:/data/db
    

    flask:
        build: .
        container_name: flask-app
        command: python -u app.py
        volumes:
            - .:/app
        ports:
            - "5000:5000"
        environment:
            - ENV=Development
        depends_on:
            - mongodb
    
volumes:
    db-data:
